Fix abandon cart quote merging issue with configurable products
dotmailer/dotmailer-magento2-extension pull request #603
Opened 2023-03-01 20:13 UTC by paco-shum

This is a clean state branch copy for https://github.com/dotmailer/dotmailer-magento2-extension/pull/601

### Original Issue:
When an abandoned cart contains configurable items, the original method won't be able to add the parent due to missing selected options on `$currentQuote->addProduct($item->getProduct());`
See screenshot as example
![Screenshot 2023-02-09 at 18 59 06](https://user-images.githubusercontent.com/49101304/218897318-c8536f70-f72f-4431-9ace-cc546e2c548a.png)

### Solution:
Using getAllVisibleItems() instead, and loop through visible items to check for simple products that are contained within a configurable product. This method is borrowed from the merge() function within Quote but slightly simplified to match the original implementation. 

### Replication steps
1. on browser A, add a configurable product to cart
2. then on browser B, add another configurable product to cart
3. on browser B, access {siteURL}/connector/email/getbasket/quote_id/{the quote created on step 1}/

The assumption
- the customer has added an item using a device e.g. phone added an item to the basket 
- the customer got an abandoned cart email and opened on another device e.g. desktop 
- the customer opened the email while they might have an item within the basket already (either from current the session or as a logged-in customer who has a cart saved)

2023-03-01 20:15 UTC, paco-shum commented
Hi @pvpcookie @sta1r here's a clean state branch. Thak you and sorry for the inconvenience.

2023-03-02 11:37 UTC, sta1r requested changes

2023-03-02 11:37 UTC, sta1r commented on Controller/Email/Getbasket.php
> -                    $currentQuote->addProduct($item->getProduct());
Is it possible that by not using `addProduct` we are removing a check here for quotes belonging to different websites? e.g. if customer drops carts on 2 different websites of the same Magento, we don't want to add products from website B to a quote for website A. 

Potentially the best way to preserve this check is to add it on L147. i.e. 'if the quote ids are different, but their website ids are the same, check missing and add'.

2023-03-02 11:37 UTC, sta1r commented on Controller/Email/Getbasket.php
> +                        $quoteItem->setQty($quoteItem->getQty() + $item->getQty());
We vote to remove this line. On balance we think it's not expected behaviour to sum the quantities. If you are at home and add x product to the cart, then on your way to work on the bus you add the same product to another cart, it doesn't mean you want 2x that product.

2023-03-09 00:44 UTC, paco-shum commented
Hmm, I have tried the following,

1. on browser A, add a configurable product to cart
2. then on browser B, in another store, add another configurable product to cart
3. on browser B, access {siteURL}/connector/email/getbasket/quote_id/{the quote created on step 1}/
Note: both store have the same item available

on this line there is a Quote load function (also should this be loadActive?)
https://github.com/dotmailer/dotmailer-magento2-extension/blob/83e74a4c96881c486b58e5f894144477127b5449/Controller/Email/Getbasket.php#L111

so by this line there won't be any quote ID available (null) assuming the quote is not available within the current website so it will just return to the base URL 
https://github.com/dotmailer/dotmailer-magento2-extension/blob/83e74a4c96881c486b58e5f894144477127b5449/Controller/Email/Getbasket.php#L114

2023-03-09 16:58 UTC, sta1r commented on Controller/Email/Getbasket.php
> -                    $currentQuote->addProduct($item->getProduct());
@paco-shum based on your reply and some further testing on our end, we don't think you need anything else. If the quotes are for different websites Magento won't allow quote A to be merged with quote B. Store ids don't matter because quotes update their store_id whenever the customer switches store view.

2023-03-09 16:58 UTC, sta1r approved these changes

2023-03-09 17:00 UTC, sertlab approved these changes
I'm approving this.

2023-03-09 17:08 UTC, merged

2023-03-09 17:10 UTC, sta1r commented
@paco-shum Thanks again for your contribution! Release goes out next week.

2023-03-15 11:38 UTC, sta1r commented
@paco-shum FYI this has been released in v4.20.3: https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.20.3